### PR TITLE
New textures & tweaks

### PR DESCRIPTION
**Pull request by WenXin20**
- Tweaked flower textures.
- Slot Icons now use the vanilla style.
- Tweaked Victini Spawn Block model & texture.
- Heatran Spawn now uses Minecraft's Magma texture.
- New Bricks, Spectral Glass, Ruby/Sapphire Ore textures.
- Temporal & Inverted Logs now have an animated texture.
- New leaf blocks now work for both fast and fancy graphics.
- Tweaked Distortic Mirror texture to align when multiple are placed together.
- Tweaked Ruby/Sapphire Block textures to match the recently changed gem texture.
- Tweaked some gui textures, such as the Pokécenter to match the new block texture.
___
- Tweaked recipes to use forge dye tags.
- Added a couple of stonecutter recipes.
- Added flowers to the `minecraft:small_flowers` tag
___
- Mushrooms & flowers now break instantly when punched.
___
- Fixed Sky Brick name in the lang file.
___
- Cosmic Dust Ore can now be silk touched/fortuned.

### CODE REVIEW

**Comment by NelkGames** [comment]
hey, the blocks that make up the Legendary Tree cannot be leaf blocks, the structure will come apart in seconds, so I made it as solid blocks.
and another, the Deep Cave flower "b1_flower" has to stay as it is, it was a special addition from a friend, I don't want to change his sprite :I

**Comment by WenXin20** [comment]
Alright, I'll revert the texture change for the flower.
For the leaf blocks, could we change the tree structure so that it uses the persistent state as tree so that it doesn't decay?

**Comment by NelkGames** [comment]
if you can do that, I think it's okay to change these blocks
and if you need the map where it was built, just send a message on the discord that I send to you

**Comment by WenXin20** [comment]
This should fix it. I was able to use the NBT Explorer program to add the persistent property to it. Is this the only structure with the leaves?
I tried to use `/locate` in the ultra dimension to find the Legendary Tree to be sure it worked properly, but every time I did, the log would start saying `Null dimInfo, can't check for structure!`, and the dimension stops loading.

**Comment by NelkGames** [comment]
it's because it doesn't appear in that dimension
if you look for a structure where it is not generated, minecraft is doing an infinite search

**Comment by WenXin20** [comment]
Ah, where can I find the tree? I thought it usually says "cannot find structure nearby" if its not in the dimension. That's what it does in the overworld at least.

**Pull request merged**
